# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dataview_element.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DataElement(object):
    def setupUi(self, DataElement):
        DataElement.setObjectName("DataElement")
        DataElement.resize(733, 221)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DataElement.sizePolicy().hasHeightForWidth())
        DataElement.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(DataElement)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pages = QtWidgets.QStackedWidget(DataElement)
        self.pages.setObjectName("pages")
        self.page_1d = QtWidgets.QWidget()
        self.page_1d.setObjectName("page_1d")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page_1d)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.graphicsView = InteractiveDataplot1d(self.page_1d)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_2.addWidget(self.graphicsView)
        self.options_group = QtWidgets.QFrame(self.page_1d)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.options_group.sizePolicy().hasHeightForWidth())
        self.options_group.setSizePolicy(sizePolicy)
        self.options_group.setMaximumSize(QtCore.QSize(100, 16777215))
        self.options_group.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.options_group.setFrameShadow(QtWidgets.QFrame.Raised)
        self.options_group.setObjectName("options_group")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.options_group)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.options_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(self.options_group)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout.addWidget(self.spinBox)
        self.label_2 = QtWidgets.QLabel(self.options_group)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.options_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.load_from_vmrk = QtWidgets.QPushButton(self.options_group)
        self.load_from_vmrk.setObjectName("load_from_vmrk")
        self.verticalLayout.addWidget(self.load_from_vmrk)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.load = QtWidgets.QPushButton(self.options_group)
        self.load.setObjectName("load")
        self.verticalLayout.addWidget(self.load)
        self.close = QtWidgets.QPushButton(self.options_group)
        self.close.setObjectName("close")
        self.verticalLayout.addWidget(self.close)
        self.horizontalLayout_2.addWidget(self.options_group)
        self.pages.addWidget(self.page_1d)
        self.page_2d = QtWidgets.QWidget()
        self.page_2d.setObjectName("page_2d")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_2d)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.graphicsView_1 = InteractiveDataplot2d(self.page_2d)
        self.graphicsView_1.setObjectName("graphicsView_1")
        self.horizontalLayout_3.addWidget(self.graphicsView_1)
        self.options_group_1 = QtWidgets.QFrame(self.page_2d)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.options_group_1.sizePolicy().hasHeightForWidth())
        self.options_group_1.setSizePolicy(sizePolicy)
        self.options_group_1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.options_group_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.options_group_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.options_group_1.setObjectName("options_group_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.options_group_1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.load_1 = QtWidgets.QPushButton(self.options_group_1)
        self.load_1.setObjectName("load_1")
        self.verticalLayout_2.addWidget(self.load_1)
        self.close_1 = QtWidgets.QPushButton(self.options_group_1)
        self.close_1.setObjectName("close_1")
        self.verticalLayout_2.addWidget(self.close_1)
        self.horizontalLayout_3.addWidget(self.options_group_1)
        self.pages.addWidget(self.page_2d)
        self.horizontalLayout.addWidget(self.pages)

        self.retranslateUi(DataElement)
        self.pages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DataElement)

    def retranslateUi(self, DataElement):
        _translate = QtCore.QCoreApplication.translate
        DataElement.setWindowTitle(_translate("DataElement", "Form"))
        self.label.setText(_translate("DataElement", "Select channel:"))
        self.label_2.setText(_translate("DataElement", "Set start in video:"))
        self.load_from_vmrk.setText(_translate("DataElement", "Load from VMRK"))
        self.load.setText(_translate("DataElement", "Load ..."))
        self.close.setText(_translate("DataElement", "Close"))
        self.load_1.setText(_translate("DataElement", "Load ..."))
        self.close_1.setText(_translate("DataElement", "Close"))

from interactivedataplot1d import InteractiveDataplot1d
from interactivedataplot2d import InteractiveDataplot2d
