# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_data_processor.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(831, 438)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(831, 438))
        MainWindow.setMaximumSize(QtCore.QSize(831, 438))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 515, 324))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.layout_for_processing_jobs = QtWidgets.QVBoxLayout()
        self.layout_for_processing_jobs.setObjectName("layout_for_processing_jobs")
        self.verticalLayout_4.addLayout(self.layout_for_processing_jobs)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.remove_jobs = QtWidgets.QPushButton(self.groupBox)
        self.remove_jobs.setObjectName("remove_jobs")
        self.horizontalLayout_3.addWidget(self.remove_jobs)
        self.start_processing = QtWidgets.QPushButton(self.groupBox)
        self.start_processing.setObjectName("start_processing")
        self.horizontalLayout_3.addWidget(self.start_processing)
        self.new_job = QtWidgets.QPushButton(self.groupBox)
        self.new_job.setObjectName("new_job")
        self.horizontalLayout_3.addWidget(self.new_job)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.output_files = QtWidgets.QTextEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_files.sizePolicy().hasHeightForWidth())
        self.output_files.setSizePolicy(sizePolicy)
        self.output_files.setObjectName("output_files")
        self.verticalLayout_2.addWidget(self.output_files)
        self.clear_output_files = QtWidgets.QPushButton(self.groupBox_2)
        self.clear_output_files.setObjectName("clear_output_files")
        self.verticalLayout_2.addWidget(self.clear_output_files)
        self.horizontalLayout.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 831, 17))
        self.menubar.setObjectName("menubar")
        self.menuNew_job = QtWidgets.QMenu(self.menubar)
        self.menuNew_job.setObjectName("menuNew_job")
        self.menuManage_Jobs = QtWidgets.QMenu(self.menubar)
        self.menuManage_Jobs.setObjectName("menuManage_Jobs")
        self.menuMore = QtWidgets.QMenu(self.menubar)
        self.menuMore.setObjectName("menuMore")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCompute_1D_Movement_Score = QtWidgets.QAction(MainWindow)
        self.actionCompute_1D_Movement_Score.setObjectName("actionCompute_1D_Movement_Score")
        self.actionCompute_2D_Movement_Score = QtWidgets.QAction(MainWindow)
        self.actionCompute_2D_Movement_Score.setObjectName("actionCompute_2D_Movement_Score")
        self.actionEEG_spectrogram = QtWidgets.QAction(MainWindow)
        self.actionEEG_spectrogram.setObjectName("actionEEG_spectrogram")
        self.actionEEG_freqeuncy_power = QtWidgets.QAction(MainWindow)
        self.actionEEG_freqeuncy_power.setObjectName("actionEEG_freqeuncy_power")
        self.actionEEG_spectrogram_2 = QtWidgets.QAction(MainWindow)
        self.actionEEG_spectrogram_2.setObjectName("actionEEG_spectrogram_2")
        self.actionRemove_all_jobs = QtWidgets.QAction(MainWindow)
        self.actionRemove_all_jobs.setObjectName("actionRemove_all_jobs")
        self.actionStart_all_jobs = QtWidgets.QAction(MainWindow)
        self.actionStart_all_jobs.setObjectName("actionStart_all_jobs")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.menuNew_job.addAction(self.actionCompute_1D_Movement_Score)
        self.menuNew_job.addAction(self.actionCompute_2D_Movement_Score)
        self.menuNew_job.addSeparator()
        self.menuNew_job.addAction(self.actionEEG_freqeuncy_power)
        self.menuNew_job.addAction(self.actionEEG_spectrogram_2)
        self.menuManage_Jobs.addAction(self.actionRemove_all_jobs)
        self.menuManage_Jobs.addAction(self.actionStart_all_jobs)
        self.menuMore.addAction(self.actionClose)
        self.menubar.addAction(self.menuNew_job.menuAction())
        self.menubar.addAction(self.menuManage_Jobs.menuAction())
        self.menubar.addAction(self.menuMore.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Data Processor"))
        self.groupBox.setTitle(_translate("MainWindow", "Processing Jobs"))
        self.remove_jobs.setText(_translate("MainWindow", "Remove all processing jobs"))
        self.start_processing.setText(_translate("MainWindow", "Start all processing jobs"))
        self.new_job.setText(_translate("MainWindow", "New job ..."))
        self.groupBox_2.setTitle(_translate("MainWindow", "Output files"))
        self.clear_output_files.setText(_translate("MainWindow", "Clear output"))
        self.menuNew_job.setTitle(_translate("MainWindow", "New processing job"))
        self.menuManage_Jobs.setTitle(_translate("MainWindow", "Manage processing jobs"))
        self.menuMore.setTitle(_translate("MainWindow", "More"))
        self.actionCompute_1D_Movement_Score.setText(_translate("MainWindow", "1D Movement Score ..."))
        self.actionCompute_2D_Movement_Score.setText(_translate("MainWindow", "2D Movement Score ..."))
        self.actionEEG_spectrogram.setText(_translate("MainWindow", "EEG spectrogram"))
        self.actionEEG_freqeuncy_power.setText(_translate("MainWindow", "EEG freqeuncy power ..."))
        self.actionEEG_spectrogram_2.setText(_translate("MainWindow", "EEG spectrogram ..."))
        self.actionRemove_all_jobs.setText(_translate("MainWindow", "Remove all jobs"))
        self.actionStart_all_jobs.setText(_translate("MainWindow", "Start all jobs"))
        self.actionClose.setText(_translate("MainWindow", "Close"))

