# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(909, 614)
        MainWindow.setMinimumSize(QtCore.QSize(100, 100))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = VideoPlot(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout.addWidget(self.frame)
        self.frame1 = QtWidgets.QFrame(self.widget)
        self.frame1.setObjectName("frame1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.select_roi = QtWidgets.QPushButton(self.frame1)
        self.select_roi.setObjectName("select_roi")
        self.verticalLayout_3.addWidget(self.select_roi)
        self.load = QtWidgets.QPushButton(self.frame1)
        self.load.setObjectName("load")
        self.verticalLayout_3.addWidget(self.load)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.jump_to_end = QtWidgets.QPushButton(self.frame1)
        self.jump_to_end.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/jump_to_end.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.jump_to_end.setIcon(icon)
        self.jump_to_end.setObjectName("jump_to_end")
        self.verticalLayout_3.addWidget(self.jump_to_end)
        self.pushButton = QtWidgets.QPushButton(self.frame1)
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/jump_to_start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.frame_back = QtWidgets.QPushButton(self.frame1)
        self.frame_back.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/frame_back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.frame_back.setIcon(icon2)
        self.frame_back.setObjectName("frame_back")
        self.verticalLayout_3.addWidget(self.frame_back)
        self.frame_forward = QtWidgets.QPushButton(self.frame1)
        self.frame_forward.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/frame_forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.frame_forward.setIcon(icon3)
        self.frame_forward.setObjectName("frame_forward")
        self.verticalLayout_3.addWidget(self.frame_forward)
        self.stop_play = QtWidgets.QPushButton(self.frame1)
        self.stop_play.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_play.setIcon(icon4)
        self.stop_play.setObjectName("stop_play")
        self.verticalLayout_3.addWidget(self.stop_play)
        self.play = QtWidgets.QPushButton(self.frame1)
        self.play.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play.setIcon(icon5)
        self.play.setObjectName("play")
        self.verticalLayout_3.addWidget(self.play)
        self.horizontalLayout.addWidget(self.frame1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalSlider = QtWidgets.QSlider(self.widget)
        self.horizontalSlider.setMaximum(1000)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addWidget(self.horizontalSlider)
        self.scrollArea = DataListView(self.splitter)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.QScrollAreaContent = QtWidgets.QWidget()
        self.QScrollAreaContent.setGeometry(QtCore.QRect(0, 0, 893, 55))
        self.QScrollAreaContent.setObjectName("QScrollAreaContent")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.QScrollAreaContent)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.add_datadisplay = QtWidgets.QPushButton(self.QScrollAreaContent)
        self.add_datadisplay.setObjectName("add_datadisplay")
        self.verticalLayout_4.addWidget(self.add_datadisplay)
        self.scrollArea.setWidget(self.QScrollAreaContent)
        self.verticalLayout_2.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 909, 17))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuProcess_Data = QtWidgets.QMenu(self.menubar)
        self.menuProcess_Data.setObjectName("menuProcess_Data")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen_Video = QtWidgets.QAction(MainWindow)
        self.actionOpen_Video.setObjectName("actionOpen_Video")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionSelect_Region_of_interest_ROI = QtWidgets.QAction(MainWindow)
        self.actionSelect_Region_of_interest_ROI.setObjectName("actionSelect_Region_of_interest_ROI")
        self.actionExtract_Motion_from_Videos = QtWidgets.QAction(MainWindow)
        self.actionExtract_Motion_from_Videos.setObjectName("actionExtract_Motion_from_Videos")
        self.actionCompute_2D_Histogram_Representation = QtWidgets.QAction(MainWindow)
        self.actionCompute_2D_Histogram_Representation.setObjectName("actionCompute_2D_Histogram_Representation")
        self.actionCompute_Power_Spectrum_EEG = QtWidgets.QAction(MainWindow)
        self.actionCompute_Power_Spectrum_EEG.setObjectName("actionCompute_Power_Spectrum_EEG")
        self.actionStart_Data_Processor = QtWidgets.QAction(MainWindow)
        self.actionStart_Data_Processor.setObjectName("actionStart_Data_Processor")
        self.start_data_processor = QtWidgets.QAction(MainWindow)
        self.start_data_processor.setObjectName("start_data_processor")
        self.menuFile.addAction(self.actionOpen_Video)
        self.menuFile.addAction(self.actionSelect_Region_of_interest_ROI)
        self.menuFile.addAction(self.actionClose)
        self.menuProcess_Data.addAction(self.start_data_processor)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuProcess_Data.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PYVIMO-VIEWER"))
        self.select_roi.setText(_translate("MainWindow", "Select ROI"))
        self.load.setText(_translate("MainWindow", "Load ..."))
        self.add_datadisplay.setText(_translate("MainWindow", "+"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuProcess_Data.setTitle(_translate("MainWindow", "Process Data"))
        self.actionOpen_Video.setText(_translate("MainWindow", "Open Video"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionSelect_Region_of_interest_ROI.setText(_translate("MainWindow", "Select Region of interest (ROI)"))
        self.actionExtract_Motion_from_Videos.setText(_translate("MainWindow", "Extract Motion from Videos"))
        self.actionCompute_2D_Histogram_Representation.setText(_translate("MainWindow", "Compute 2D Histogram Representation"))
        self.actionCompute_Power_Spectrum_EEG.setText(_translate("MainWindow", "Compute Power Spectrum (EEG)"))
        self.actionStart_Data_Processor.setText(_translate("MainWindow", "Open Data Processor"))
        self.start_data_processor.setText(_translate("MainWindow", "Start Data-Processor"))

from datalistview import DataListView
from videoplot import VideoPlot
